features = []
homepage = "http://ilovequentin.it/"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
min_version = "0.38"
name = "I LOVE QUENTIN"
summaryLength = 30
tags = []
theme = "default"
title = "I Love Quentin"
[author]
homepage = "http://ilovequentin.it"
name = "Vincenzo Prencipe"
[frontmatter]
date = ["date", "publishDate", "lastmod"]
expiryDate = ["expiryDate"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
[[menu.header]]
name = "Blog"
url = "/blog"
weight = 2
[[menu.header]]
name = "Home"
url = "/"
weight = 1
[params]
avatar = "https://drive.google.com/uc?export=view&id=1hlKlQ17D6Pf1VIwmIFXcpt2wkv6fOHEm"
date_format = "6 January 2006"
description = "Non è con le chiacchiere che uscirai da questa merda"
home = "Home"
subDescription = "Jules Winnfield - Pulp Fiction"
