---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content/disclaimer
  label: Disclaimer
  create: all
  match: "**/*"
- type: directory
  path: content/me
  label: Me
  create: all
  match: "**/*"
- type: directory
  path: content/contatti
  label: Contatti
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/privacy-policy
  label: Privacy policy
  create: all
  match: "**/*"
upload_dir: static/uploads/wp-content/uploads
public_path: "/uploads/wp-content/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.47.1
